In [1]:
import pandas as pd
pd.set_option('display.max_columns', 40)
#导入数据
train_data=pd.read_csv('used_car_train_20200313.csv',sep=' ')
train_data#训练集

,SaleID,name,regDate,model,brand,bodyType,fuelType,gearbox,power,kilometer,notRepairedDamage,regionCode,seller,offerType,creatDate,price,v_0,v_1,v_2,v_3,v_4,v_5,v_6,v_7,v_8,v_9,v_10,v_11,v_12,v_13,v_14
0,0,736,20040402,30.0,6,1.0,0.0,0.0,60,12.5,0.0,1046,0,0,20160404,1850,43.357796,3.966344,0.050257,2.159744,1.143786,0.235676,0.101988,0.129549,0.022816,0.097462,-2.881803,2.804097,-2.420821,0.795292,0.914762
1,1,2262,20030301,40.0,1,2.0,0.0,0.0,0,15.0,-,4366,0,0,20160309,3600,45.305273,5.236112,0.137925,1.380657,-1.422165,0.264777,0.121004,0.135731,0.026597,0.020582,-4.900482,2.096338,-1.030483,-1.722674,0.245522
2,2,14874,20040403,115.0,15,1.0,0.0,0.0,163,12.5,0.0,2806,0,0,20160402,6222,45.978359,4.823792,1.319524,-0.998467,-0.996911,0.251410,0.114912,0.165147,0.062173,0.027075,-4.846749,1.803559,1.565330,-0.832687,-0.229963
3,3,71865,19960908,109.0,10,0.0,0.0,1.0,193,15.0,0.0,434,0,0,20160312,2400,45.687478,4.492574,-0.050616,0.883600,-2.228079,0.274293,0.110300,0.121964,0.033395,0.000000,-4.509599,1.285940,-0.501868,-2.438353,-0.478699
4,4,111080,20120103,110.0,5,1.0,0.0,0.0,68,5.0,0.0,6977,0,0,20160313,5200,44.383511,2.031433,0.572169,-1.571239,2.246088,0.228036,0.073205,0.091880,0.078819,0.121534,-1.896240,0.910783,0.931110,2.834518,1.923482
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,149995,163978,20000607,121.0,10,4.0,0.0,1.0,163,15.0,0.0,4576,0,0,20160327,5900,45.316543,-3.139095,-1.269707,-0.736609,-1.505820,0.280264,0.000310,0.048441,0.071158,0.019174,1.988114,-2.983973,0.589167,-1.304370,-0.302592
149996,149996,184535,20091102,116.0,11,0.0,0.0,0.0,125,10.0,0.0,2826,0,0,20160312,9500,45.972058,-3.143764,-0.023523,-2.366699,0.698012,0.253217,0.000777,0.084079,0.099681,0.079371,1.839166,-2.774615,2.553994,0.924196,-0.272160
149997,149997,147587,20101003,60.0,11,1.0,1.0,0.0,90,6.0,0.0,3302,0,0,20160328,7500,44.733481,-3.105721,0.595454,-2.279091,1.423661,0.233353,0.000705,0.118872,0.100118,0.097914,2.439812,-1.630677,2.290197,1.891922,0.414931
149998,149998,45907,20060312,34.0,10,3.0,1.0,0.0,156,15.0,0.0,1877,0,0,20160401,4999,45.658634,-3.204785,-0.441680,-1.179812,0.620680,0.256369,0.000252,0.081479,0.083558,0.081498,2.075380,-2.633719,1.414937,0.431981,-1.659014
149999,149999,177672,19990204,19.0,28,6.0,0.0,1.0,193,12.5,0.0,235,0,0,20160305,4700,45.536383,-3.200326,-1.612893,-0.067144,-1.396166,0.284475,0.000000,0.040072,0.062543,0.025819,1.978453,-3.179913,0.031724,-1.483350,-0.342674

In [2]:
#探索一下train_data数据
train_data['regDate']#时间都出来了，但是这些数字不能直接放到模型里面用，需要将其转换成数字，就是以最小的时间开始经历的时间
#所以找出这时间里面的 最小值，其他的值减去这个最小值，这一列的数据就处理完了

0         20040402
1         20030301
2         20040403
3         19960908
4         20120103
            ...
149995    20000607
149996    20091102
149997    20101003
149998    20060312
149999    19990204
Name: regDate, Length: 150000, dtype: int64

In [3]:
import numpy as np 
np.min(train_data['regDate'])#找出这个最小的时间

19910001

In [4]:
temp=pd.to_datetime(train_data['regDate'],format='%Y%m%d',errors='coerce')#转换为时间戳格式
temp

0        2004-04-02
1        2003-03-01
2        2004-04-03
3        1996-09-08
4        2012-01-03
            ...
149995   2000-06-07
149996   2009-11-02
149997   2010-10-03
149998   2006-03-12
149999   1999-02-04
Name: regDate, Length: 150000, dtype: datetime64[ns]

In [5]:
min_date=pd.to_datetime('19910101',format='%Y%m%d')#将最小的时间转换为时间戳格式
min_date

Timestamp('1991-01-01 00:00:00')

In [6]:
#相减一下看看
(temp-min_date).dt.days

0         4840.0
1         4442.0
2         4841.0
3         2077.0
4         7672.0
           ...
149995    3445.0
149996    6880.0
149997    7215.0
149998    5549.0
149999    2956.0
Name: regDate, Length: 150000, dtype: float64

In [7]:
#然后将train_data['regDate']汽车注册时间 转换一下，减去最小的时间得到的结果,得到汽车的展示时间
train_data['regTime']=(pd.to_datetime(train_data['regDate'],format='%Y%m%d',errors='coerce')-min_date ).dt.days
train_data['regTime']

0         4840.0
1         4442.0
2         4841.0
3         2077.0
4         7672.0
           ...
149995    3445.0
149996    6880.0
149997    7215.0
149998    5549.0
149999    2956.0
Name: regTime, Length: 150000, dtype: float64

In [8]:
#同理可以将train_data['creatDate']汽车售卖时间 转换一下，减去最小的时间得到的结果,得到汽车的损耗时间
train_data['creatTime']=(pd.to_datetime(train_data['creatDate'],format='%Y%m%d',errors='coerce')-min_date ).dt.days
train_data['creatTime']

0         9225
1         9199
2         9223
3         9202
4         9203
          ...
149995    9217
149996    9202
149997    9218
149998    9222
149999    9195
Name: creatTime, Length: 150000, dtype: int64

In [9]:
#creatTime-regTime就得到了汽车的使用时间
train_data['usedTime']=train_data['creatTime']-train_data['regTime']
train_data['usedTime']

0         4385.0
1         4757.0
2         4382.0
3         7125.0
4         1531.0
           ...
149995    5772.0
149996    2322.0
149997    2003.0
149998    3673.0
149999    6239.0
Name: usedTime, Length: 150000, dtype: float64

In [10]:
#同样把 test_data 也读取进来也处理一下
test_data=pd.read_csv('used_car_testB_20200421.csv',sep=' ')
test_data

,SaleID,name,regDate,model,brand,bodyType,fuelType,gearbox,power,kilometer,notRepairedDamage,regionCode,seller,offerType,creatDate,v_0,v_1,v_2,v_3,v_4,v_5,v_6,v_7,v_8,v_9,v_10,v_11,v_12,v_13,v_14
0,200000,133777,20000501,67.0,0,1.0,0.0,0.0,101,15.0,0.0,5019,0,0,20160308,42.142061,-3.094739,-0.721300,1.466344,1.009846,0.236520,0.000241,0.105319,0.046233,0.094522,3.619512,-0.280607,-2.019761,0.978828,0.803322
1,200001,61206,19950211,19.0,6,2.0,0.0,0.0,73,6.0,0.0,1505,0,0,20160310,43.907034,-3.244605,-0.766430,1.276718,-1.065338,0.261518,0.000000,0.120323,0.046784,0.035385,2.997376,-1.406705,-1.020884,-1.349990,-0.200542
2,200002,67829,20090606,5.0,5,4.0,0.0,0.0,120,5.0,-,1776,0,0,20160309,45.389665,3.372384,-0.965565,-2.447316,0.624268,0.261691,0.090836,0.000000,0.079655,0.073586,-3.951084,-0.433467,0.918964,1.634604,1.027173
3,200003,8892,20020601,22.0,9,1.0,0.0,0.0,58,15.0,0.0,26,0,0,20160314,42.788775,4.035052,-0.217403,1.708806,1.119165,0.236050,0.101777,0.098950,0.026830,0.096614,-2.846788,2.800267,-2.524610,1.076819,0.461610
4,200004,76998,20030301,46.0,6,0.0,NaN,0.0,116,15.0,0.0,738,0,0,20160306,43.670763,-3.135382,-1.134107,0.470315,0.134032,0.257000,0.000000,0.066732,0.057771,0.068852,2.839010,-1.659801,-0.924142,0.199423,0.451014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,249995,111443,20041005,4.0,4,0.0,NaN,1.0,150,15.0,-,5564,0,0,20160309,46.321013,-3.304401,0.073363,-0.622359,-0.778349,0.263668,0.000292,0.141804,0.076393,0.039272,2.072901,-2.531869,1.716978,-1.063437,0.326587
49996,249996,152834,20130409,65.0,1,0.0,0.0,0.0,179,4.0,0.0,5220,0,0,20160323,48.086547,-3.318641,0.965881,-2.672160,0.357440,0.255310,0.000991,0.155868,0.108425,0.067841,1.358504,-3.290295,4.269809,0.140524,0.556221
49997,249997,132531,20041211,4.0,4,0.0,0.0,1.0,147,12.5,0.0,3795,0,0,20160316,46.145279,-3.305263,-0.015283,-0.288329,-0.687112,0.262933,0.000318,0.141872,0.071968,0.042966,2.165658,-2.417885,1.370612,-1.073133,0.270602
49998,249998,143405,20020702,40.0,1,4.0,0.0,1.0,176,15.0,0.0,61,0,0,20160327,45.507088,-3.197006,-1.141252,-0.434930,-1.845040,0.282106,0.000023,0.067483,0.067526,0.009006,2.030114,-2.939244,0.569078,-1.718245,0.316379
49999,249999,78202,20090708,32.0,8,1.0,0.0,0.0,0,3.0,0.0,4158,0,0,20160401,44.289471,4.181452,0.547068,-0.775841,1.789601,0.231449,0.103947,0.096027,0.062328,0.110180,-3.689090,2.032376,0.109157,2.202828,0.847469

In [11]:
#同理测试集的数据也这样处理一下
test_data['regTime']=(pd.to_datetime(test_data['regDate'],format='%Y%m%d',errors='coerce')-min_date ).dt.days
test_data['creatTime']=(pd.to_datetime(test_data['creatDate'],format='%Y%m%d',errors='coerce')-min_date ).dt.days
test_data['usedTime']=test_data['creatTime']-test_data['regTime']

In [12]:
train_data.info()#信息探索一下

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 34 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   SaleID             150000 non-null  int64
 1   name               150000 non-null  int64
 2   regDate            150000 non-null  int64
 3   model              149999 non-null  float64
 4   brand              150000 non-null  int64
 5   bodyType           145494 non-null  float64
 6   fuelType           141320 non-null  float64
 7   gearbox            144019 non-null  float64
 8   power              150000 non-null  int64
 9   kilometer          150000 non-null  float64
 10  notRepairedDamage  150000 non-null  object
 11  regionCode         150000 non-null  int64
 12  seller             150000 non-null  int64
 13  offerType          150000 non-null  int64
 14  creatDate          150000 non-null  int64
 15  price              150000 non-null  int64
 16  v_0                150000 non-null  float64
 17  v_1                150000 non-null  float64
 18  v_2                150000 non-null  float64
 19  v_3                150000 non-null  float64
 20  v_4                150000 non-null  float64
 21  v_5                150000 non-null  float64
 22  v_6                150000 non-null  float64
 23  v_7                150000 non-null  float64
 24  v_8                150000 non-null  float64
 25  v_9                150000 non-null  float64
 26  v_10               150000 non-null  float64
 27  v_11               150000 non-null  float64
 28  v_12               150000 non-null  float64
 29  v_13               150000 non-null  float64
 30  v_14               150000 non-null  float64
 31  regTime            138653 non-null  float64
 32  creatTime          150000 non-null  int64
 33  usedTime           138653 non-null  float64
dtypes: float64(22), int64(11), object(1)
memory usage: 38.9+ MB

In [13]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SaleID             50000 non-null  int64
 1   name               50000 non-null  int64
 2   regDate            50000 non-null  int64
 3   model              50000 non-null  float64
 4   brand              50000 non-null  int64
 5   bodyType           48496 non-null  float64
 6   fuelType           47076 non-null  float64
 7   gearbox            48032 non-null  float64
 8   power              50000 non-null  int64
 9   kilometer          50000 non-null  float64
 10  notRepairedDamage  50000 non-null  object
 11  regionCode         50000 non-null  int64
 12  seller             50000 non-null  int64
 13  offerType          50000 non-null  int64
 14  creatDate          50000 non-null  int64
 15  v_0                50000 non-null  float64
 16  v_1                50000 non-null  float64
 17  v_2                50000 non-null  float64
 18  v_3                50000 non-null  float64
 19  v_4                50000 non-null  float64
 20  v_5                50000 non-null  float64
 21  v_6                50000 non-null  float64
 22  v_7                50000 non-null  float64
 23  v_8                50000 non-null  float64
 24  v_9                50000 non-null  float64
 25  v_10               50000 non-null  float64
 26  v_11               50000 non-null  float64
 27  v_12               50000 non-null  float64
 28  v_13               50000 non-null  float64
 29  v_14               50000 non-null  float64
 30  regTime            46264 non-null  float64
 31  creatTime          50000 non-null  int64
 32  usedTime           46264 non-null  float64
dtypes: float64(22), int64(10), object(1)
memory usage: 12.6+ MB

In [14]:
#看一下那个 notRepairedDamage 的数据分布情况
train_data['notRepairedDamage'].value_counts()#发现有缺失值，需要补全，

0.0    111361
-       24324
1.0     14315
Name: notRepairedDamage, dtype: int64

In [15]:
#采用众数补全的方法
train_data['notRepairedDamage'].replace('-','0.0',inplace=True)
train_data['notRepairedDamage'].value_counts()#缺失值已经补完了

0.0    135685
1.0     14315
Name: notRepairedDamage, dtype: int64

In [16]:
#看看测试里面是不是也缺失了，要是缺失了，用同样的方法
test_data['notRepairedDamage'].value_counts()#发现有缺失值，需要补全，

0.0    37224
-       8069
1.0     4707
Name: notRepairedDamage, dtype: int64

In [17]:
#采用众数补全的方法,同样的方法  复制粘贴过来，把train 换成test
test_data['notRepairedDamage'].replace('-','0.0',inplace=True)
test_data['notRepairedDamage'].value_counts()#发现有缺失值，需要补全

0.0    45293
1.0     4707
Name: notRepairedDamage, dtype: int64

In [18]:
#将数据调整为float64
train_data['notRepairedDamage']=train_data['notRepairedDamage'].astype('float64')
test_data['notRepairedDamage']=test_data['notRepairedDamage'].astype('float64')

In [19]:
#数据类型转换完之后再看看info()
train_data.info()
print("分界线","-"*90)
test_data.info()#可以看到数据已经转化为float类型了

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 34 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   SaleID             150000 non-null  int64
 1   name               150000 non-null  int64
 2   regDate            150000 non-null  int64
 3   model              149999 non-null  float64
 4   brand              150000 non-null  int64
 5   bodyType           145494 non-null  float64
 6   fuelType           141320 non-null  float64
 7   gearbox            144019 non-null  float64
 8   power              150000 non-null  int64
 9   kilometer          150000 non-null  float64
 10  notRepairedDamage  150000 non-null  float64
 11  regionCode         150000 non-null  int64
 12  seller             150000 non-null  int64
 13  offerType          150000 non-null  int64
 14  creatDate          150000 non-null  int64
 15  price              150000 non-null  int64
 16  v_0                150000 non-null  float64
 17  v_1                150000 non-null  float64
 18  v_2                150000 non-null  float64
 19  v_3                150000 non-null  float64
 20  v_4                150000 non-null  float64
 21  v_5                150000 non-null  float64
 22  v_6                150000 non-null  float64
 23  v_7                150000 non-null  float64
 24  v_8                150000 non-null  float64
 25  v_9                150000 non-null  float64
 26  v_10               150000 non-null  float64
 27  v_11               150000 non-null  float64
 28  v_12               150000 non-null  float64
 29  v_13               150000 non-null  float64
 30  v_14               150000 non-null  float64
 31  regTime            138653 non-null  float64
 32  creatTime          150000 non-null  int64
 33  usedTime           138653 non-null  float64
dtypes: float64(23), int64(11)
memory usage: 38.9 MB
分界线 ------------------------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SaleID             50000 non-null  int64
 1   name               50000 non-null  int64
 2   regDate            50000 non-null  int64
 3   model              50000 non-null  float64
 4   brand              50000 non-null  int64
 5   bodyType           48496 non-null  float64
 6   fuelType           47076 non-null  float64
 7   gearbox            48032 non-null  float64
 8   power              50000 non-null  int64
 9   kilometer          50000 non-null  float64
 10  notRepairedDamage  50000 non-null  float64
 11  regionCode         50000 non-null  int64
 12  seller             50000 non-null  int64
 13  offerType          50000 non-null  int64
 14  creatDate          50000 non-null  int64
 15  v_0                50000 non-null  float64
 16  v_1                50000 non-null  float64
 17  v_2                50000 non-null  float64
 18  v_3                50000 non-null  float64
 19  v_4                50000 non-null  float64
 20  v_5                50000 non-null  float64
 21  v_6                50000 non-null  float64
 22  v_7                50000 non-null  float64
 23  v_8                50000 non-null  float64
 24  v_9                50000 non-null  float64
 25  v_10               50000 non-null  float64
 26  v_11               50000 non-null  float64
 27  v_12               50000 non-null  float64
 28  v_13               50000 non-null  float64
 29  v_14               50000 non-null  float64
 30  regTime            46264 non-null  float64
 31  creatTime          50000 non-null  int64
 32  usedTime           46264 non-null  float64
dtypes: float64(23), int64(10)
memory usage: 12.6 MB

In [20]:
#再看一下数据里面是否有缺失值
print(train_data.isnull().sum())#sum()是求和，any()是返回True Fale
print("-"*100)
test_data.isnull().sum()#sum()是求和，any()是返回True Fale

SaleID                   0
name                     0
regDate                  0
model                    1
brand                    0
bodyType              4506
fuelType              8680
gearbox               5981
power                    0
kilometer                0
notRepairedDamage        0
regionCode               0
seller                   0
offerType                0
creatDate                0
price                    0
v_0                      0
v_1                      0
v_2                      0
v_3                      0
v_4                      0
v_5                      0
v_6                      0
v_7                      0
v_8                      0
v_9                      0
v_10                     0
v_11                     0
v_12                     0
v_13                     0
v_14                     0
regTime              11347
creatTime                0
usedTime             11347
dtype: int64
----------------------------------------------------------------------------------------------------

SaleID                  0
name                    0
regDate                 0
model                   0
brand                   0
bodyType             1504
fuelType             2924
gearbox              1968
power                   0
kilometer               0
notRepairedDamage       0
regionCode              0
seller                  0
offerType               0
creatDate               0
v_0                     0
v_1                     0
v_2                     0
v_3                     0
v_4                     0
v_5                     0
v_6                     0
v_7                     0
v_8                     0
v_9                     0
v_10                    0
v_11                    0
v_12                    0
v_13                    0
v_14                    0
regTime              3736
creatTime               0
usedTime             3736
dtype: int64

In [21]:
print("训练集大小：{}".format(train_data.shape))
print("测试集大小：{}".format(test_data.shape))

训练集大小：(150000, 34)
测试集大小：(50000, 33)

In [22]:
#找到数值类型的特征
numerical_cols=train_data.select_dtypes(exclude='object').columns
numerical_cols

Index(['SaleID', 'name', 'regDate', 'model', 'brand', 'bodyType', 'fuelType',
       'gearbox', 'power', 'kilometer', 'notRepairedDamage', 'regionCode',
       'seller', 'offerType', 'creatDate', 'price', 'v_0', 'v_1', 'v_2', 'v_3',
       'v_4', 'v_5', 'v_6', 'v_7', 'v_8', 'v_9', 'v_10', 'v_11', 'v_12',
       'v_13', 'v_14', 'regTime', 'creatTime', 'usedTime'],
      dtype='object')

In [23]:
#找到 object 类型的特征
train_data.select_dtypes(include='object').columns
#发现没有，因为全部已经转成数值类型了    你们训练集全是数值了   可以拿去训练了吧

Index([], dtype='object')

In [24]:
train_data['SaleID'].value_counts()#这个saleID 跟最后的预测price是没有关系的，就把他给去掉吧，还有那个price也给去掉吧

2047      1
113949    1
15661     1
13612     1
3371      1
         ..
8913      1
10960     1
53967     1
56014     1
0         1
Name: SaleID, Length: 150000, dtype: int64

In [25]:
#去掉SaleID和price 就得到了训练集
feature_cols=[col for col in numerical_cols if col not in ['SaleID','price'] ]
feature_cols

['name',
 'regDate',
 'model',
 'brand',
 'bodyType',
 'fuelType',
 'gearbox',
 'power',
 'kilometer',
 'notRepairedDamage',
 'regionCode',
 'seller',
 'offerType',
 'creatDate',
 'v_0',
 'v_1',
 'v_2',
 'v_3',
 'v_4',
 'v_5',
 'v_6',
 'v_7',
 'v_8',
 'v_9',
 'v_10',
 'v_11',
 'v_12',
 'v_13',
 'v_14',
 'regTime',
 'creatTime',
 'usedTime']

In [26]:
#提取特征列
X_data=train_data[feature_cols]#训练集特征
Y_data=train_data['price']#训练集标签
X_test=test_data[feature_cols]#测试集特征

In [27]:
#定义一个统计函数方便了解数据的分布
def show_stats(data):
    print("最小值：{}".format(np.min(data)))
    print("最大值：{}".format(np.max(data)))
    print("最大小值之差：{}".format(np.ptp(data)))
    print("均值：{}".format(np.mean(data)))
    print("标准差：{}".format(np.std(data)))
    print("方差：{}".format(np.var(data)))

In [28]:
#训练集price的统计情况
show_stats(Y_data)

最小值：11
最大值：99999
最大小值之差：99988
均值：5923.327333333334
标准差：7501.973469876438
方差：56279605.94272992

In [29]:
train_data.corr()

,SaleID,name,regDate,model,brand,bodyType,fuelType,gearbox,power,kilometer,notRepairedDamage,regionCode,seller,offerType,creatDate,price,v_0,v_1,v_2,v_3,v_4,v_5,v_6,v_7,v_8,v_9,v_10,v_11,v_12,v_13,v_14,regTime,creatTime,usedTime
SaleID,1.000000,-0.002299,-0.001373,0.000659,-0.001754,-0.005163,-0.001584,0.001153,0.000873,-0.001115,-0.003008,-0.001078,0.000055,NaN,-0.001449,-0.001043,-0.001831,-0.000390,0.001237,-0.000034,-0.000494,-0.001380,-0.000397,0.001164,-0.000046,-0.000749,0.000983,0.001276,0.000249,0.000162,-0.000209,-0.002685,0.002564,0.002699
name,-0.002299,1.000000,-0.037638,0.016080,0.040678,0.034532,0.014880,0.026104,0.000236,-0.007613,0.011158,0.005603,-0.001257,NaN,-0.005056,0.002030,-0.125450,-0.638309,-0.003404,-0.047349,0.006417,-0.057710,-0.638191,0.057199,0.235341,0.008455,0.576758,-0.258582,0.090897,0.007558,-0.011303,-0.025793,-0.007233,0.025760
regDate,-0.001373,-0.037638,1.000000,0.148780,0.033199,0.102864,0.276227,0.142631,0.097446,-0.492852,-0.136967,-0.004783,-0.001606,NaN,-0.001293,0.611959,0.524815,0.103922,0.142413,-0.796583,0.260285,0.020100,0.107282,-0.037048,0.761804,0.146139,-0.249871,-0.184640,0.704787,0.412246,0.177898,0.998943,0.001479,-0.998932
model,0.000659,0.016080,0.148780,1.000000,0.358765,0.207208,0.048767,0.019314,0.031245,-0.087445,-0.010141,0.010241,0.000984,NaN,-0.004383,0.136983,0.091031,0.019805,-0.037685,-0.215659,0.426664,-0.019701,0.015419,-0.100753,0.211149,0.423526,-0.058674,-0.079661,0.110157,0.400001,-0.513733,0.144539,-0.003587,-0.144556
brand,-0.001754,0.040678,0.033199,0.358765,1.000000,0.114116,-0.079566,0.012914,-0.022391,-0.096262,0.023074,-0.002326,0.000311,NaN,-0.001466,-0.043799,-0.101214,-0.025579,-0.036106,-0.000582,0.343755,-0.069206,-0.031185,-0.050022,0.015200,0.352137,0.043222,0.007571,-0.070912,0.320933,-0.207713,0.028218,-0.000627,-0.028222
bodyType,-0.005163,0.034532,0.102864,0.207208,0.114116,1.000000,0.118717,0.099966,0.079632,-0.053212,-0.017969,0.017380,0.000309,NaN,0.002508,0.241303,0.303539,-0.010096,-0.172383,-0.250790,-0.052972,0.398335,-0.009374,-0.399415,0.220308,-0.051773,-0.082708,-0.293019,0.210039,-0.030675,-0.288897,0.104169,-0.000644,-0.104173
fuelType,-0.001584,0.014880,0.276227,0.048767,-0.079566,0.118717,1.000000,0.171692,0.059315,0.099446,-0.030807,-0.012507,-0.001822,NaN,-0.001081,0.200536,0.279984,-0.002663,0.067672,-0.293114,-0.095064,0.081457,0.001499,0.000487,0.279369,-0.128720,-0.075217,-0.137755,0.302333,-0.049669,-0.021656,0.274515,-0.009303,-0.274562
gearbox,0.001153,0.026104,0.142631,0.019314,0.012914,0.099966,0.171692,1.000000,0.156706,-0.046807,-0.032288,-0.022640,-0.001420,NaN,-0.002538,0.329075,0.306703,-0.004298,0.054411,-0.254030,-0.238739,0.124329,0.002201,0.011876,0.238381,-0.258017,-0.080558,-0.145925,0.291374,-0.203841,-0.044204,0.139194,-0.000103,-0.139196
power,0.000873,0.000236,0.097446,0.031245,-0.022391,0.079632,0.059315,0.156706,1.000000,-0.019631,-0.024311,0.004422,-0.001739,NaN,0.001280,0.219834,0.215028,0.023746,-0.031487,-0.185342,-0.141013,0.119727,0.025648,-0.060397,0.155956,-0.140203,-0.092717,-0.122107,0.161990,-0.103430,-0.023808,0.095313,0.004792,-0.095285
kilometer,-0.001115,-0.007613,-0.492852,-0.087445,-0.096262,-0.053212,0.099446,-0.046807,-0.019631,1.000000,0.087160,-0.010590,0.001583,NaN,0.004718,-0.440519,-0.225034,-0.022228,-0.110375,0.402502,-0.214861,0.049502,-0.024664,-0.017835,-0.407686,-0.149422,0.083358,0.066542,-0.370153,-0.285158,-0.120389,-0.515652,-0.002688,0.515636
notRepairedDamage,-0.003008,0.011158,-0.136967,-0.010141,0.023074,-0.017969,-0.030807,-0.032288,-0.024311,0.087160,1.000000,0.010233,-0.000839,NaN,-0.002819,-0.157523,-0.144928,-0.018277,-0.036004,0.221958,0.040709,-0.028152,-0.018567,0.007686,-0.204789,0.068055,0.061486,0.059881,-0.198598,-0.022958,-0.044979,-0.133133,-0.005862,0.133102
regionCode,-0.001078,0.005603,-0.004783,0.010241,-0.002326,0.017380,-0.012507,-0.022640,0.004422,-0.010590,0.010233,1.000000,-0.001813,NaN,0.002717,0.014036,-0.004880,0.029612,0.005159,-0.010416,-0.014232,-0.002506,0.028838,0.000609,-0.001227,-0.016659,-0.024333,0.016807,0.002261,-0.001976,-0.009702,-0.000469,0.006002,0.000499
seller,0.000055,-0.001257,-0.001606,0.000984,0.000311,0.000309,-0.001822,-0.001420,-0.001739,0.001583,-0.000839,-0.001813,1.000000,NaN,-0.000382,-0.002004,-0.003340,-0.002316,-0.001868,0.006937,0.004256,-0.000641,-0.002242,-0.000421,-0.005144,0.005572,0.003026,0.000182,-0.006003,0.000881,-0.003140,-0.001754,-0.001598,0.001746
offerType,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
creatDate,-0.001449,-0.005056,-0.001293,-0.004383,-0.001466,0.002508,-0.001081,-0.002538,0.001280,0.004718,-0.002819,0.002717,-0.000382,NaN,1.000000,0.002955,0.005167,0.009998,-0.003633,0.001520,-0.004367,0.005612,0.010005,-0.004129,-0.005214,-0.003350,-0.010391,0.000596,-0.003077,-0.004312,0.005001,-0.000410,0.401354,0.002335
price,-0.001043,0.002030,0.611959,0.136983,-0.043799,0.241303,0.200536,0.329075,0.219834,-0.440519,-0.157523,0.014036,-0.002004,NaN,0.002955,1.000000,0.628397,0.060914,0.085322,-0.730946,-0.147085,0.164317,0.068970,-0.053024,0.685798,-0.206205,-0.246175,-0.275320,0.692823,-0.013993,0.035911,0.610593,0.016916,-0.610510
v_0,-0.001831,-0.125450,0.524815,0.091031,-0.101214,0.303539,0.279984,0.306703,0.215028,-0.225034,-0.144928,-0.004880,-0.003340,NaN,0.005167,0.628397,1.000000,0.245049,-0.452591,-0.710480,-0.259714,0.726250,0.243783,-0.584363,0.514149,-0.186243,-0.582943,-0.667809,0.415711,-0.136938,-0.039809,0.570150,0.016299,-0.570067
v_1,-0.000390,-0.638309,0.103922,0.019805,-0.025579,-0.010096,-0.002663,-0.004298,0.023746,-0.022228,-0.018277,0.029612,-0.002316,NaN,0.009998,0.060914,0.245049,1.000000,-0.001133,-0.001915,-0.000468,0.109303,0.999415,-0.110806,-0.298966,-0.007698,-0.921904,0.370445,-0.087593,0.017349,0.002143,0.089543,0.013452,-0.089474
v_2,0.001237,-0.003404,0.142413,-0.037685,-0.036106,-0.172383,0.067672,0.054411,-0.031487,-0.110375,-0.036004,0.005159,-0.001868,NaN,-0.003633,0.085322,-0.452591,-0.001133,1.000000,0.001224,-0.001021,-0.921857,0.023877,0.973689,0.180285,-0.236164,0.274341,0.800915,0.535270,-0.055376,-0.013785,0.235481,-0.008427,-0.235522
v_3,-0.000034,-0.047349,-0.796583,-0.215659,-0.000582,-0.250790,-0.293114,-0.254030,-0.185342,0.402502,0.221958,-0.010416,0.006937,NaN,0.001520,-0.730946,-0.710480,-0.001915,0.001224,1.000000,-0.001694,-0.233412,-0.000747,0.191278,-0.933161,0.079292,0.247385,0.429777,-0.811301,-0.246052,-0.058561,-0.809768,-0.010034,0.809721
v_4,-0.000494,0.006417,0.260285,0.426664,0.343755,-0.052972,-0.095064,-0.238739,-0.141013,-0.214861,0.040709,-0.014232,0.004256,NaN,-0.004367,-0.147085,-0.259714,-0.000468,-0.001021,-0.001694,1.000000,-0.259739,-0.011275,-0.054241,0.051741,0.962928,0.071116,0.110660,-0.134611,0.934580,-0.178518,0.263879,-0.005589,-0.263903
v_5,-0.001380,-0.057710,0.020100,-0.019701,-0.069206,0.398335,0.081457,0.124329,0.119727,0.049502,-0.028152,-0.002506,-0.000641,NaN,0.005612,0.164317,0.726250,0.109303,-0.921857,-0.233412,-0.259739,1.000000,0.091229,-0.939385,0.010686,-0.050343,-0.440588,-0.845954,-0.258521,-0.162689,0.037804,-0.014439,0.013224,0.014512
v_6,-0.000397,-0.638191,0.107282,0.015419,-0.031185,-0.009374,0.001499,0.002201,0.025648,-0.024664,-0.018567,0.028838,-0.002242,NaN,0.010005,0.068970,0.243783,0.999415,0.023877,-0.000747,-0.011275,0.091229,1.000000,-0.085410,-0.294956,-0.023057,-0.917056,0.386446,-0.070238,0.000758,-0.003322,0.093595,0.013321,-0.093526
v_7,0.001164,0.057199,-0.037048,-0.100753,-0.050022,-0.399415,0.000487,0.011876,-0.060397,-0.017835,0.007686,0.000609,-0.000421,NaN,-0.004129,-0.053024,-0.584363,-0.110806,0.973689,0.191278,-0.054241,-0.939385,-0.085410,1.000000,0.028695,-0.264091,0.410014,0.813175,0.385378,-0.154535,-0.020218,-0.009285,-0.011269,0.009223
v_8,-0.000046,0.235341,0.761804,0.211149,0.015200,0.220308,0.279369,0.238381,0.155956,-0.407686,-0.204789,-0.001227,-0.005144,NaN,-0.005214,0.685798,0.514149,-0.298966,0.180285,-0.933161,0.051741,0.010686,-0.294956,0.028695,1.000000,-0.063577,0.094497,-0.369353,0.882121,0.250423,0.030416,0.768312,0.003576,-0.768296
v_9,-0.000749,0.008455,0.146139,0.423526,0.352137,-0.051773,-0.128720,-0.258017,-0.140203,-0.149422,0.068055,-0.016659,0.005572,NaN,-0.003350,-0.206205,-0.186243,-0.007698,-0.236164,0.079292,0.962928,-0.050343,-0.023057,-0.264091,-0.063577,1.000000,0.026562,-0.056200,-0.313634,0.880545,-0.214151,0.146484,-0.004339,-0.146505
v_10,0.000983,0.576758,-0.249871,-0.058674,0.043222,-0.082708,-0.075217,-0.080558,-0.092717,0.083358,0.061486,-0.024333,0.003026,NaN,-0.010391,-0.246175,-0.582943,-0.921904,0.274341,0.247385,0.071116,-0.440588,-0.917056,0.410014,0.094497,0.026562,1.000000,0.006306,0.001289,-0.000580,0.002244,-0.236960,-0.017705,0.236871
v_11,0.001276,-0.258582,-0.184640,-0.079661,0.007571,-0.293019,-0.137755,-0.145925,-0.122107,0.066542,0.059881,0.016807,0.000182,NaN,0.000596,-0.275320,-0.667809,0.370445,0.800915,0.429777,0.110660,-0.845954,0.386446,0.813175,-0.369353,-0.056200,0.006306,1.000000,0.006695,-0.001671,-0.001156,-0.204743,-0.006908,0.204716
v_12,0.000249,0.090897,0.704787,0.110157,-0.070912,0.210039,0.302333,0.291374,0.161990,-0.370153,-0.198598,0.002261,-0.006003,NaN,-0.003077,0.692823,0.415711,-0.087593,0.535270,-0.811301,-0.134611,-0.258521,-0.070238,0.385378,0.882121,-0.313634,0.001289,0.006695,1.000000,0.001512,0.002045,0.742756,0.003433,-0.742735
v_13,0.000162,0.007558,0.412246,0.400001,0.320933,-0.030675,-0.049669,-0.203841,-0.103430,-0.285158,-0.022958,-0.001976,0.000881,NaN,-0.004312,-0.013993,-0.136938,0.017349,-0.055376,-0.246052,0.934580,-0.162689,0.000758,-0.154535,0.250423,0.880545,-0.000580,-0.001671,0.001512,1.000000,0.001419,0.411235,-0.002164,-0.411246
v_14,-0.000209,-0.011303,0.177898,-0.513733,-0.207713,-0.288897,-0.021656,-0.044204,-0.023808,-0.120389,-0.044979,-0.009702,-0.003140,NaN,0.005001,0.035911,-0.039809,0.002143,-0.013785,-0.058561,-0.178518,0.037804,-0.003322,-0.020218,0.030416,-0.214151,0.002244,-0.001156,0.002045,0.001419,1.000000,0.174935,0.004440,-0.174917
regTime,-0.002685,-0.025793,0.998943,0.144539,0.028218,0.104169,0.274515,0.139194,0.095313,-0.515652,-0.133133,-0.000469,-0.001754,NaN,-0.000410,0.610593,0.570150,0.089543,0.235481,-0.809768,0.263879,-0.014439,0.093595,-0.009285,0.768312,0.146484,-0.236960,-0.204743,0.742756,0.411235,0.174935,1.000000,0.002573,-0.999988
creatTime,0.002564,-0.007233,0.001479,-0.003587,-0.000627,-0.000644,-0.009303,-0.000103,0.004792,-0.002688,-0.005862,0.006002,-0.001598,NaN,0.401354,0.016916,0.016299,0.013452,-0.008427,-0.010034,-0.005589,0.013224,0.013321,-0.011269,0.003576,-0.004339,-0.017705,-0.006908,0.003433,-0.002164,0.004440,0.002573,1.000000,0.002240
usedTime,0.002699,0.025760,-0.998932,-0.144556,-0.028222,-0.104173,-0.274562,-0.139196,-0.095285,0.515636,0.133102,0.000499,0.001746,NaN,0.002335,-0.610510,-0.570067,-0.089474,-0.235522,0.809721,-0.263903,0.014512,-0.093526,0.009223,-0.768296,-0.146505,0.236871,0.204716,-0.742735,-0.411246,-0.174917,-0.999988,0.002240,1.000000

In [30]:
train_data.corr()['price']

SaleID              -0.001043
name                 0.002030
regDate              0.611959
model                0.136983
brand               -0.043799
bodyType             0.241303
fuelType             0.200536
gearbox              0.329075
power                0.219834
kilometer           -0.440519
notRepairedDamage   -0.157523
regionCode           0.014036
seller              -0.002004
offerType                 NaN
creatDate            0.002955
price                1.000000
v_0                  0.628397
v_1                  0.060914
v_2                  0.085322
v_3                 -0.730946
v_4                 -0.147085
v_5                  0.164317
v_6                  0.068970
v_7                 -0.053024
v_8                  0.685798
v_9                 -0.206205
v_10                -0.246175
v_11                -0.275320
v_12                 0.692823
v_13                -0.013993
v_14                 0.035911
regTime              0.610593
creatTime            0.016916
usedTime            -0.610510
Name: price, dtype: float64

In [32]:
#缺失值用-1补全
X_data=X_data.fillna(-1)
X_test=X_test.fillna(-1)

In [33]:
#补全完了就可以用模型来预测了 先试试线性回归
from sklearn.linear_model import LinearRegression
model=LinearRegression()
print("生成的模型:{}".format(model))#模型已经造好了
model.fit(X_data,Y_data)#训练
pridict_y_xgb=model.predict(X_test)
print("xgboost的预测结果的统计情况:")
show_stats( pridict_y_xgb)

生成的模型:LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)
xgboost的预测结果的统计情况:
最小值：-15098.120254516602
最大值：45968.11215591431
最大小值之差：61066.23241043091
均值：5911.374206256027
标准差：6219.6916407278795
方差：38684564.10574026